title: "Scrawl Jekyll Theme"
description: >-
  Based on
  [Primer](https://github.com/pages-themes/primer),
  inspired by
  [Minimal](https://github.com/pages-themes/minimal)

sass:
  style: compressed

exclude:
  - '*.gemspec'
  - 'Gemfile*'
  - bin
  - '*.gem'
  - Makefile
  - LICENSE
  - README.md

plugins:
  # force included by GitHub Pages
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  # required by {% seo %} tag
  - jekyll-seo-tag

permalink: pretty
