title: "Jekyll Theme Scrawl"
description: >
  Scrawl is a Jekyll theme based on <a href="https://github.com/pages-themes/minimal">Minimal</a>

sass:
  style: compressed

exclude:
  - '*.gemspec'
  - 'Gemfile*'
  - bin
  - LICENSE.txt
  - README.md

theme: jekyll-theme-scrawl

plugins:
  - "jekyll-github-metadata"
