title: "Dhruv Sheth"
description: >-
  Website about Dhruv Sheth. Undergraduate 
  student studying Computer Science at Caltech.
  Hacking robots in free time.

sass:
  style: compressed

exclude:
  - _site
  - '*.gem'
  - '*.gemspec'
  - 'Gemfile*'
  - bin
  - docker-compose.yml
  - LICENSE
  - Makefile

plugins:
  # force included by GitHub Pages
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  # required by {% seo %} tag
  - jekyll-seo-tag
  - jekyll-include-cache

permalink: pretty
