title: "Scrawl Jekyll Theme"
description: >
  Based on
  <a href="https://github.com/pages-themes/primer">Primer</a>,
  inspired by
  <a href="https://github.com/pages-themes/minimal">Minimal</a>

sass:
  style: compressed

exclude:
  - '*.gemspec'
  - 'Gemfile*'
  - bin
  - LICENSE.txt
  - README.md

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag

default_width: fixed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      hide_in_nav: false

collections:
  pages:
    output: true
    permalink: /:categories/:name
