version: "3"
services:
  jekyll:
    image: lightster/github-pages:latest
    volumes:
      - $PWD:/jekyll/source:delegated
    ports:
      - ${JEKYLL_PORT:-80}
    networks:
      default:
      buoy:
        aliases:
          - "${BUOY_HOST:-scrawl}"
    environment:
      - JEKYLL_PORT

networks:
  buoy:
    external:
      name: buoy
